package com.sk89q.worldedit.internal.command;

/**
 * Command call listener for WorldEdit.
 * This is a stub class - in a real implementation, this would be generated by Piston annotation processing.
 */
public class CommandCallListener {

    // This is a placeholder for the generated command call listener functionality
    // The actual implementation would be generated by Piston's annotation processor
}
