package com.sk89q.worldedit.command;

/**
 * Biome commands registration for WorldEdit.
 * This is a stub class - in a real implementation, this would be generated by Piston annotation processing.
 */
public class BiomeCommandsRegistration {

    // This is a placeholder for the generated biome commands registration functionality
    // The actual implementation would be generated by Piston's annotation processor
}
