package com.sk89q.worldedit.extension.platform;

/**
 * Command registration handler for WorldEdit.
 * This is a stub class - in a real implementation, this would be generated by Piston annotation processing.
 */
public class CommandRegistration {

    // This is a placeholder for the generated command registration functionality
    // The actual implementation would be generated by Piston's annotation processor
}
